### ISSUE TITLE
Issues with running ANGSD with -maxHetFreq filter

### ISSUE THREAD

**Issue by lexiebsturm** [z0on/AFS-analysis-with-moments#5]
Hi Misha,
I am having trouble generating the two pops mafs file needed to generate the SAF data for both populations. When I try to run it, I keep getting error "-maxHetFreq is unknown will exit." At first I thought this was a version issue so I requested that the HPC staff here at FAU update the angsd module. I am now running angsd version: 0.929-19-gb2b41b5 (htslib: 1.9-139-gce7daf7) but still having the same issue. Is there another issue that may be causing the problem? Your advice would be greatly appreciated!

Thanks

**Comment by z0on** [comment]
Hi Lexie - sorry I missed you last two emails... - congrats on the Mcav
paper!!! great job!

maxHetFreq is indeed a new filter -  my angsd is 0.933-25-g5955d69 , let
them get the newest one!

**Comment by lexiebsturm** [comment]
Thanks Misha!! Your 2bRAD workshop/code made it happen :) they updated ANGSD on the cluster and the filter works now. 
Many thanks, 
Lexie
